import Head from 'next/head'
import React from 'react'
import Footer from '../components/Footer'
import Header from '../components/Header'

const Format = ({ children }) => {
    return (
        <>
            <Head>
                <title>Blogger Man</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Header />
            <main>{children}</main>
            <Footer />
        </>
    )
}

export default Format