const data = () => {
    Trending = [
        {
            id: 1,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 2,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 3,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 4,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 5,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
    ],
    Posts = [
        {
            id: 1,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 2,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 3,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 4,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 5,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
    ],
    Popular = [
        {
            id: 1,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 2,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 3,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 4,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
        {
            id: 5,
            title: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Sed, asperiores.",
            subtitle: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Molestiae harum necessitatibus repellendus, quae libero tempora!",
            category: "Business, Travel",
            img: '/images/img1.jpg',
            description: "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Quas, dicta. Repellendus, veritatis. Error neque nihil ipsa ex placeat assumenda voluptates doloribus accusantium dolore fugit mollitia consectetur nam eaque vero ipsum perferendis animi, impedit similique unde voluptatem et aut consequuntur! Saepe obcaecati dolores earum voluptates veniam!",
            published: 'Jun 3, 2022',
            author: {
                name: "Flying High",
                img: '/images/author/author1.jpg',
                description: "CEO and Founder",
            },
        },
    ]
}